version: 1
services:
  piko:
    build: .
    ports:
      - 8000:8000  # HTTP
      - 8001:8001  # Admin API
      - 8002:8002  # Proxy
    environment:
      - CLUSTER_JOIN=piko
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  caddy:
    image: caddy:latest
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - piko
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
