version: "3.4"
services:
  piko-1:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-1-
    hostname: piko-1
    volumes:
      - type: bind
        source: ${PWD}/config/piko.yaml
        target: /etc/piko.yaml
        read_only: true

  piko-2:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-2-
    hostname: piko-2
    volumes:
      - type: bind
        source: ${PWD}/config/piko.yaml
        target: /etc/piko.yaml
        read_only: true

  piko-3:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
      - --config.path
      - /etc/piko.yaml
      - --cluster.node-id-prefix
      - piko-3-
    hostname: piko-3
    volumes:
      - type: bind
        source: ${PWD}/config/piko.yaml
        target: /etc/piko.yaml
        read_only: true

  load-balancer:
    image: caddy:latest
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - "piko-1"
      - "piko-2"
      - "piko-3"
    ports:
      - 8180:8000
      - 8181:8001
      - 8182:8002

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
    volumes:
      - ./config/prometheus:/etc/prometheus/
    depends_on:
      - "piko-1"
      - "piko-2"
      - "piko-3"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - 3000:3000

networks:
  piko-network:
    driver: bridge
    name: piko-network
