version: "3.4"
services:
  piko:
    image: ghcr.io/andydunstall/piko:latest
    command:
      - server
    hostname: piko
    ports:
      - 8000
      - 8001
      - 8002
    expose:
      - 8000
      - 8001
      - 8002
